//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from assets/antlr/lib/Spells.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISpellsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SpellsBaseListener : ISpellsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.spell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpell([NotNull] SpellsParser.SpellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.spell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpell([NotNull] SpellsParser.SpellContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.imperative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperative([NotNull] SpellsParser.ImperativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.imperative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperative([NotNull] SpellsParser.ImperativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.moveUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveUnit([NotNull] SpellsParser.MoveUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.moveUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveUnit([NotNull] SpellsParser.MoveUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.spawnUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpawnUnit([NotNull] SpellsParser.SpawnUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.spawnUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpawnUnit([NotNull] SpellsParser.SpawnUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnit([NotNull] SpellsParser.UnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnit([NotNull] SpellsParser.UnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.unitType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitType([NotNull] SpellsParser.UnitTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.unitType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitType([NotNull] SpellsParser.UnitTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.unitName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitName([NotNull] SpellsParser.UnitNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.unitName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitName([NotNull] SpellsParser.UnitNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.unitDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitDescription([NotNull] SpellsParser.UnitDescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.unitDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitDescription([NotNull] SpellsParser.UnitDescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.unitBehaviour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitBehaviour([NotNull] SpellsParser.UnitBehaviourContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.unitBehaviour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitBehaviour([NotNull] SpellsParser.UnitBehaviourContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] SpellsParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] SpellsParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] SpellsParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] SpellsParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMove([NotNull] SpellsParser.MoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMove([NotNull] SpellsParser.MoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirection([NotNull] SpellsParser.DirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirection([NotNull] SpellsParser.DirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.directionUp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionUp([NotNull] SpellsParser.DirectionUpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.directionUp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionUp([NotNull] SpellsParser.DirectionUpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.directionDown"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionDown([NotNull] SpellsParser.DirectionDownContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.directionDown"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionDown([NotNull] SpellsParser.DirectionDownContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.directionLeft"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionLeft([NotNull] SpellsParser.DirectionLeftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.directionLeft"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionLeft([NotNull] SpellsParser.DirectionLeftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.directionRight"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionRight([NotNull] SpellsParser.DirectionRightContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.directionRight"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionRight([NotNull] SpellsParser.DirectionRightContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.directionRandom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionRandom([NotNull] SpellsParser.DirectionRandomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.directionRandom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionRandom([NotNull] SpellsParser.DirectionRandomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger([NotNull] SpellsParser.TriggerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger([NotNull] SpellsParser.TriggerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpellsParser.startCombat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartCombat([NotNull] SpellsParser.StartCombatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpellsParser.startCombat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartCombat([NotNull] SpellsParser.StartCombatContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
