//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from assets/antlr/lib/Units.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="UnitsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IUnitsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnit([NotNull] UnitsParser.UnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnit([NotNull] UnitsParser.UnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitType([NotNull] UnitsParser.UnitTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitType([NotNull] UnitsParser.UnitTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitName([NotNull] UnitsParser.UnitNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitName([NotNull] UnitsParser.UnitNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitDescription([NotNull] UnitsParser.UnitDescriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitDescription([NotNull] UnitsParser.UnitDescriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitBehaviour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitBehaviour([NotNull] UnitsParser.UnitBehaviourContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitBehaviour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitBehaviour([NotNull] UnitsParser.UnitBehaviourContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] UnitsParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] UnitsParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] UnitsParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] UnitsParser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMove([NotNull] UnitsParser.MoveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMove([NotNull] UnitsParser.MoveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirection([NotNull] UnitsParser.DirectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirection([NotNull] UnitsParser.DirectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionUp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectionUp([NotNull] UnitsParser.DirectionUpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionUp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectionUp([NotNull] UnitsParser.DirectionUpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionDown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectionDown([NotNull] UnitsParser.DirectionDownContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionDown"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectionDown([NotNull] UnitsParser.DirectionDownContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectionLeft([NotNull] UnitsParser.DirectionLeftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectionLeft([NotNull] UnitsParser.DirectionLeftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectionRight([NotNull] UnitsParser.DirectionRightContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectionRight([NotNull] UnitsParser.DirectionRightContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionRandom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectionRandom([NotNull] UnitsParser.DirectionRandomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionRandom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectionRandom([NotNull] UnitsParser.DirectionRandomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrigger([NotNull] UnitsParser.TriggerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrigger([NotNull] UnitsParser.TriggerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.startCombat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartCombat([NotNull] UnitsParser.StartCombatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.startCombat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartCombat([NotNull] UnitsParser.StartCombatContext context);
}
