//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from assets/antlr/lib/Units.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUnitsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class UnitsBaseListener : IUnitsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnit([NotNull] UnitsParser.UnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnit([NotNull] UnitsParser.UnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitType([NotNull] UnitsParser.UnitTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitType([NotNull] UnitsParser.UnitTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitName([NotNull] UnitsParser.UnitNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitName([NotNull] UnitsParser.UnitNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitDescription([NotNull] UnitsParser.UnitDescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitDescription([NotNull] UnitsParser.UnitDescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.unitBehaviour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitBehaviour([NotNull] UnitsParser.UnitBehaviourContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.unitBehaviour"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitBehaviour([NotNull] UnitsParser.UnitBehaviourContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] UnitsParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] UnitsParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] UnitsParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] UnitsParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMove([NotNull] UnitsParser.MoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMove([NotNull] UnitsParser.MoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirection([NotNull] UnitsParser.DirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirection([NotNull] UnitsParser.DirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionUp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionUp([NotNull] UnitsParser.DirectionUpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionUp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionUp([NotNull] UnitsParser.DirectionUpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionDown"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionDown([NotNull] UnitsParser.DirectionDownContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionDown"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionDown([NotNull] UnitsParser.DirectionDownContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionLeft"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionLeft([NotNull] UnitsParser.DirectionLeftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionLeft"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionLeft([NotNull] UnitsParser.DirectionLeftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionRight"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionRight([NotNull] UnitsParser.DirectionRightContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionRight"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionRight([NotNull] UnitsParser.DirectionRightContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.directionRandom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectionRandom([NotNull] UnitsParser.DirectionRandomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.directionRandom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectionRandom([NotNull] UnitsParser.DirectionRandomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger([NotNull] UnitsParser.TriggerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger([NotNull] UnitsParser.TriggerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UnitsParser.startCombat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartCombat([NotNull] UnitsParser.StartCombatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UnitsParser.startCombat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartCombat([NotNull] UnitsParser.StartCombatContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
